[package]
name = "nessyrs"
version = "0.1.0"
authors = ["boki1 <kristoimenov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
lazy_static = "1.4.0"
